// Official HOSA Canada competitive-event guideline documents, by season.
//
// Sourced 2026-07-04 from hosacanada.org (2026-2027 live page) and the
// Wayback Machine snapshots of the unpublished 2023-2026 pages. Entries
// whose original file has been removed from the live server point at the
// archived copy instead (`archived: true`). LINKS ONLY - no PDF bytes in
// this repo (house rule: document bytes live in object storage, never git).

export interface OfficialGuideline {
  title: string;
  url: string;
  /** Served from the Wayback Machine because the original was removed. */
  archived?: boolean;
}

export const OFFICIAL_GUIDELINES: ReadonlyArray<{
  year: string;
  items: ReadonlyArray<OfficialGuideline>;
}> = [
  {
    year: "2026–2027",
    items: [
      { title: "Rules and Regulations", url: "https://hosa.org/wp-content/uploads/2025/08/25-26-GRR-8.27.pdf" },
      { title: "Dress Code", url: "https://hosa.org/wp-content/uploads/2025/08/25-26-HOSA-Appendix-D-Dress-Code-8.11-.docx.pdf" },
      { title: "Behavioral Health", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/BH-Combined_Jan-_26.pdf" },
      { title: "Human Growth and Development", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/HGD-Combined_Jan-_26.pdf" },
      { title: "Medical Law and Ethics", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/MLE-Combined_Jan-_26.pdf" },
      { title: "Medical Math", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/MM-Combined_Jan-_26.pdf" },
      { title: "Medical Spelling", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/MS-Combined_Jan-_26.pdf" },
      { title: "Medical Terminology", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/MT-Combined_Jan-_26.pdf" },
      { title: "Nutrition", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/NUT-Combined_Jan-_26.pdf" },
      { title: "Pathophysiology", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/PAT-Combined_Jan-_26.pdf" },
      { title: "Biomedical Debate", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/BD-Combined_Jan-_26.pdf" },
      { title: "Community Awareness", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/CA-Combined_Jan-_26.pdf" },
      { title: "Creative Problem Solving", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/CPS-Combined_Jan-_26.pdf" },
      { title: "Forensic Science", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/FS-Combined_Jan-_26.pdf" },
      { title: "HOSA Bowl", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/HB-Combined_Jan-_26.pdf" },
      { title: "Medical Innovation", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/MI-Combined_Jan-_26.pdf" },
      { title: "Biotechnology (NEW)", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/BT-Combined_Jan-_26.pdf" },
      { title: "Clinical Laboratory Science", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/CL-Combined_Jan-_26.pdf" },
      { title: "Clinical Nursing", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/CN-Combined_Jan-_26.pdf" },
      { title: "Clinical Specialty", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/CS-Combined_Jan-_26.pdf" },
      { title: "Dental Science", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/DS-Combined_Jan-_26.pdf" },
      { title: "Pharmacy Science", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/RX-Combined_Jan-_26.pdf" },
      { title: "Physical Therapy", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/PT-Combined_Jan-_26.pdf" },
      { title: "Sports Medicine", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/SM-Combined_Jan-_26.pdf" },
      { title: "Veterinary Science", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/VS-Combined_Jan-_26.pdf" },
      { title: "CPR/First Aid", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/CPR-Combined_Jan-_26.pdf" },
      { title: "Emergency Medical Technician", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/EMT-Combined_Jan-_26.pdf" },
      { title: "Epidemiology", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/EP-Combined_Jan-_26.pdf" },
      { title: "Mental Health Promotion", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/MHP-Combined_Jan-_26.pdf" },
      { title: "Public Health", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/PH-Combined_Jan-_26.pdf" },
      { title: "Researched Persuasive Speaking", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/RPS-Combined_Jan-_26.pdf" },
      { title: "Research Poster", url: "https://hosacanada.org/home/wp-content/uploads/2026/01/RP-Combined_Jan-_26.pdf" },
      { title: "Leadership", url: "https://hosa.org/wp-content/uploads/2025/09/25-26-ATC-Leadership-FINAL-Aug31.pdf" },
      { title: "Occupational Health & Safety", url: "https://hosa.org/wp-content/uploads/2025/08/25-26-ATC-OccSafetyHealth-FINAL-Aug26.pdf" },
    ],
  },
  {
    year: "2025–2026",
    items: [
      { title: "Rules and Regulations", url: "https://web.archive.org/web/20250911091634/https://hosa.org/wp-content/uploads/2024/11/24-25-GRR-Final.pdf", archived: true },
      { title: "Dress Code", url: "https://hosa.org/wp-content/uploads/2025/08/25-26-HOSA-Appendix-D-Dress-Code-8.11-.docx.pdf" },
      { title: "Behavioral Health", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/BH-merged.pdf" },
      { title: "Human Growth and Development", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/HGD-merged.pdf" },
      { title: "Medical Law and Ethics", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MLE-merged.pdf" },
      { title: "Medical Math", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MM-merged.pdf" },
      { title: "Medical Spelling", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MS-merged.pdf" },
      { title: "Medical Terminology", url: "https://hosacanada.org/home/wp-content/uploads/2025/02/MT-merged.pdf" },
      { title: "Nutrition", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/NUT-merged.pdf" },
      { title: "Pathophysiology", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/PAT-merged.pdf" },
      { title: "Biomedical Debate", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/BD-merged.pdf" },
      { title: "Community Awareness", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CA-merged.pdf" },
      { title: "Creative Problem Solving", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CPS-merged.pdf" },
      { title: "Forensic Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/FS-merged.pdf" },
      { title: "HOSA Bowl", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/HB-merged.pdf" },
      { title: "Medical Innovation", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MI-merged.pdf" },
      { title: "Clinical Laboratory Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CL-merged.pdf" },
      { title: "Clinical Nursing", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CN-merged.pdf" },
      { title: "Clinical Specialty", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CS-merged.pdf" },
      { title: "Dental Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/10/DS-merged.pdf" },
      { title: "Pharmacy Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/RX-merged.pdf" },
      { title: "Physical Therapy", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/PT-merged.pdf" },
      { title: "Sports Medicine", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/SM-merged.pdf" },
      { title: "Veterinary Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/VS-merged.pdf" },
      { title: "CPR/First Aid", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CPR-merged.pdf" },
      { title: "Emergency Medical Technician", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/EMT-merged.pdf" },
      { title: "Epidemiology", url: "https://hosacanada.org/home/wp-content/uploads/2025/02/EP-merged-1.pdf" },
      { title: "Mental Health Promotion", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MH-merged.pdf" },
      { title: "Public Health", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/PH-merged.pdf" },
      { title: "Researched Persuasive Speaking", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/RPS-merged.pdf" },
      { title: "Research Poster", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/RP-merged.pdf" },
    ],
  },
  {
    year: "2024–2025",
    items: [
      { title: "Behavioral Health", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/BH-merged.pdf" },
      { title: "Human Growth and Development", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/HGD-merged.pdf" },
      { title: "Medical Law and Ethics", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MLE-merged.pdf" },
      { title: "Medical Math", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MM-merged.pdf" },
      { title: "Medical Spelling", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MS-merged.pdf" },
      { title: "Medical Terminology", url: "https://web.archive.org/web/20241008223915/https://hosacanada.org/home/wp-content/uploads/2024/09/MT-merged.pdf", archived: true },
      { title: "Nutrition", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/NUT-merged.pdf" },
      { title: "Pathophysiology", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/PAT-merged.pdf" },
      { title: "Biomedical Debate", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/BD-merged.pdf" },
      { title: "Community Awareness", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CA-merged.pdf" },
      { title: "Creative Problem Solving", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CPS-merged.pdf" },
      { title: "Forensic Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/FS-merged.pdf" },
      { title: "HOSA Bowl", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/HB-merged.pdf" },
      { title: "Medical Innovation", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MI-merged.pdf" },
      { title: "Clinical Laboratory Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CL-merged.pdf" },
      { title: "Clinical Nursing", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CN-merged.pdf" },
      { title: "Clinical Specialty", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CS-merged.pdf" },
      { title: "Dental Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/10/DS-merged.pdf" },
      { title: "Pharmacy Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/RX-merged.pdf" },
      { title: "Physical Therapy", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/PT-merged.pdf" },
      { title: "Sports Medicine", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/SM-merged.pdf" },
      { title: "Veterinary Science", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/VS-merged.pdf" },
      { title: "CPR/First Aid", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/CPR-merged.pdf" },
      { title: "Emergency Medical Technician", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/EMT-merged.pdf" },
      { title: "Epidemiology", url: "https://web.archive.org/web/20241008223915/https://hosacanada.org/home/wp-content/uploads/2024/09/EP-merged.pdf", archived: true },
      { title: "Mental Health Promotion", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/MH-merged.pdf" },
      { title: "Public Health", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/PH-merged.pdf" },
      { title: "Researched Persuasive Speaking", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/RPS-merged.pdf" },
      { title: "Research Poster", url: "https://hosacanada.org/home/wp-content/uploads/2024/09/RP-merged.pdf" },
    ],
  },
  {
    year: "2023–2024",
    items: [
      { title: "Behavioral Health", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/BH-3.pdf", archived: true },
      { title: "Human Growth and Development", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/HGD.pdf", archived: true },
      { title: "Medical Law and Ethics", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/MLE.pdf", archived: true },
      { title: "Medical Math", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/MM.pdf", archived: true },
      { title: "Medical Spelling", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/MS.pdf", archived: true },
      { title: "Medical Terminology", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/MT-1.pdf", archived: true },
      { title: "Nutrition", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/NUT.pdf", archived: true },
      { title: "Pathophysiology", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/PAT-1.pdf", archived: true },
      { title: "Biomedical Debate", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/BD.pdf", archived: true },
      { title: "Community Awareness", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/CA.pdf", archived: true },
      { title: "Creative Problem Solving", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/CPS.pdf", archived: true },
      { title: "Forensic Science", url: "https://hosacanada.org/home/wp-content/uploads/2023/10/FS.pdf" },
      { title: "HOSA Bowl", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/HB.pdf", archived: true },
      { title: "Medical Innovation", url: "https://hosacanada.org/home/wp-content/uploads/2023/10/MI.pdf" },
      { title: "Clinical Laboratory Science", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/CL.pdf", archived: true },
      { title: "Clinical Nursing", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/CN.pdf", archived: true },
      { title: "Clinical Specialty", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/CS-1.pdf", archived: true },
      { title: "Dental Science", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/DS.pdf", archived: true },
      { title: "Pharmacy Science", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/RX-1.pdf", archived: true },
      { title: "Physical Therapy", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/PT.pdf", archived: true },
      { title: "Sports Medicine", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/SM-1.pdf", archived: true },
      { title: "Veterinary Science", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/VS-1.pdf", archived: true },
      { title: "CPR/First Aid", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/CPR.pdf", archived: true },
      { title: "Emergency Medical Technician", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/EMT-1.pdf", archived: true },
      { title: "Epidemiology", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/EP-1.pdf", archived: true },
      { title: "Mental Health Promotion", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/MH-1.pdf", archived: true },
      { title: "Public Health", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/PH-1.pdf", archived: true },
      { title: "Researched Persuasive Speaking", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/RPS-1.pdf", archived: true },
      { title: "Research Poster", url: "https://web.archive.org/web/20231002174631/https://hosacanada.org/home/wp-content/uploads/2023/09/RP-1.pdf", archived: true },
    ],
  },
];
